// lib/translator.js

// Enhanced English to Urdu translation dictionary with contextual phrases
const englishToUrdu = {
  // Common words
  the: "یہ",
  and: "اور",
  or: "یا",
  but: "لیکن",
  is: "ہے",
  are: "ہیں",
  was: "تھا",
  were: "تھے",
  have: "ہے",
  has: "ہے",
  will: "گا",
  would: "گا",
  can: "سکتا",
  could: "سکتا",
  should: "چاہیے",
  may: "ہو سکتا",
  might: "ہو سکتا",

  // Enhanced contextual phrases - PRIORITY TRANSLATIONS
  "content marketing": "مواد کی مارکیٹنگ",
  "social media": "سوشل میڈیا",
  "artificial intelligence": "مصنوعی ذہانت",
  "machine learning": "مشین لرننگ",
  "data analysis": "ڈیٹا تجزیہ",
  "user experience": "صارف کا تجربہ",
  "digital marketing": "ڈیجیٹل مارکیٹنگ",
  "business strategy": "کاروباری حکمت عملی",
  "market research": "بازار کی تحقیق",
  "customer service": "کسٹمر سروس",
  "product development": "پروڈکٹ ڈیولپمنٹ",
  "project management": "پروجیکٹ مینجمنٹ",
  "quality assurance": "کوالٹی ایشورنس",
  "human resources": "انسانی وسائل",
  "financial analysis": "مالی تجزیہ",
  "risk management": "خطرات کا انتظام",
  "supply chain": "سپلائی چین",
  "market share": "مارکیٹ شیئر",
  "competitive advantage": "مسابقتی فائدہ",
  "return on investment": "سرمایہ کاری کی واپسی",
  "cost effectiveness": "لاگت کی مؤثریت",
  "performance metrics": "کارکردگی کی پیمائش",
  "key performance indicators": "اہم کارکردگی کے اشارے",
  "growth rate": "نمو کی شرح",
  "conversion rate": "تبدیلی کی شرح",
  "click through rate": "کلک تھرو ریٹ",
  "search engine optimization": "سرچ انجن آپٹیمائزیشن",
  "user interface": "یوزر انٹرفیس",
  "mobile application": "موبائل ایپلیکیشن",
  "web development": "ویب ڈیولپمنٹ",
  "software engineering": "سافٹ ویئر انجینئرنگ",
  "database management": "ڈیٹابیس مینجمنٹ",
  "cloud computing": "کلاؤڈ کمپیوٹنگ",
  "cyber security": "سائبر سیکیورٹی",
  "information technology": "انفارمیشن ٹیکنالوجی",
  "digital transformation": "ڈیجیٹل تبدیلی",
  "business intelligence": "بزنس انٹیلیجنس",
  "market analysis": "مارکیٹ تجزیہ",
  "customer satisfaction": "کسٹمر کی اطمینان",
  "brand awareness": "برانڈ آگاہی",
  "sales revenue": "فروخت کی آمدنی",
  "profit margin": "منافع کا مارجن",
  "operating costs": "آپریٹنگ اخراجات",
  "market trends": "مارکیٹ کے رجحانات",
  "industry standards": "صنعتی معیارات",
  "best practices": "بہترین طریقے",
  "strategic planning": "اسٹریٹیجک پلاننگ",
  "operational efficiency": "آپریشنل کارکردگی",
  "customer retention": "کسٹمر برقراری",
  "market penetration": "مارکیٹ میں داخلہ",
  "product lifecycle": "پروڈکٹ کی زندگی",
  "innovation management": "جدت کا انتظام",
  "technology adoption": "ٹیکنالوجی کا اپنانا",
  "digital literacy": "ڈیجیٹل خواندگی",
  "data privacy": "ڈیٹا کی پرائیویسی",
  "network security": "نیٹ ورک سیکیورٹی",
  "system integration": "سسٹم انٹیگریشن",
  "process automation": "عمل کی خودکاری",
  "workflow optimization": "ورک فلو کی بہتری",
  "resource allocation": "وسائل کی تقسیم",
  "performance evaluation": "کارکردگی کا جائزہ",
  "quality control": "کوالٹی کنٹرول",
  "continuous improvement": "مسلسل بہتری",
  "change management": "تبدیلی کا انتظام",
  "leadership development": "قیادت کی ترقی",
  "team collaboration": "ٹیم کا تعاون",
  "communication skills": "رابطے کی مہارت",
  "problem solving": "مسئلے کا حل",
  "decision making": "فیصلہ سازی",
  "critical thinking": "تنقیدی سوچ",
  "creative thinking": "تخلیقی سوچ",
  "time management": "وقت کا انتظام",
  "project planning": "پروجیکٹ کی منصوبہ بندی",
  "budget management": "بجٹ کا انتظام",
  "cost analysis": "لاگت کا تجزیہ",
  "market positioning": "مارکیٹ میں پوزیشن",
  "brand positioning": "برانڈ پوزیشننگ",
  "target audience": "ہدف کے سامعین",
  "customer segmentation": "کسٹمر کی تقسیم",
  "value proposition": "ویلیو پروپوزیشن",
  "competitive analysis": "مسابقتی تجزیہ",
  "market opportunity": "مارکیٹ کا موقع",
  "business model": "بزنس ماڈل",
  "revenue stream": "آمدنی کا ذریعہ",
  "cost structure": "لاگت کا ڈھانچہ",
  scalability: "پیمانہ بندی",
  sustainability: "پائیداری",

  // Technology terms
  technology: "ٹیکنالوجی",
  computer: "کمپیوٹر",
  internet: "انٹرنیٹ",
  website: "ویب سائٹ",
  software: "سافٹ ویئر",
  application: "ایپلیکیشن",
  development: "ترقی",
  programming: "پروگرامنگ",
  coding: "کوڈنگ",
  data: "ڈیٹا",
  database: "ڈیٹابیس",
  system: "نظام",
  network: "نیٹ ورک",
  security: "سیکیورٹی",
  artificial: "مصنوعی",
  intelligence: "ذہانت",
  machine: "مشین",
  learning: "سیکھنا",
  algorithm: "الگورتھم",
  digital: "ڈیجیٹل",
  online: "آن لائن",
  mobile: "موبائل",
  app: "ایپ",
  user: "صارف",
  interface: "انٹرفیس",
  experience: "تجربہ",
  design: "ڈیزائن",

  // Business terms
  business: "کاروبار",
  content: "مواد",
  strategy: "حکمت عملی",
  financial: "مالی",
  marketers: "مارکیٹرز",
  institute: "ادارہ",
  states: "بتاتا ہے",
  about: "تقریباً",
  using: "استعمال کر رہے ہیں",
  rut: "خرابی میں",
  marketing: "مارکیٹنگ",
  digital: "ڈیجیٹل",
  business: "کاروبار",
  technology: "ٹیکنالوجی",
  "social media": "سوشل میڈیا",
  online: "آن لائن",
  website: "ویب سائٹ",
  internet: "انٹرنیٹ",
  company: "کمپنی",
  customer: "کسٹمر",
  service: "خدمات",
  product: "پروڈکٹ",
  brand: "برانڈ",
  sales: "فروخت",
  revenue: "آمدنی",
  growth: "ترقی",
  market: "بازار",
  audience: "سامعین",
  engagement: "مشغولیت",
  analytics: "تجزیات",
  performance: "کارکردگی",
  conversion: "تبدیلی",
  optimization: "بہتری",
  campaign: "مہم",
  advertising: "اشتہارات",
  promotion: "فروغ",
  innovation: "جدت",
  solution: "حل",
  development: "ترقی",
  research: "تحقیق",
  analysis: "تجزیہ",
  report: "رپورٹ",
  data: "ڈیٹا",
  information: "معلومات",
  trends: "رجحانات",
  insights: "بصیرت",
  statistics: "اعداد و شمار",
  success: "کامیابی",
  challenges: "چیلنجز",
  opportunities: "مواقع",
  benefits: "فوائد",
  advantages: "فوائد",
  features: "خصوصیات",
  quality: "معیار",
  experience: "تجربہ",
  professional: "پیشہ ور",
  expert: "ماہر",
  leadership: "قیادت",
  management: "انتظام",
  team: "ٹیم",
  collaboration: "تعاون",
  communication: "رابطہ",
  network: "نیٹ ورک",
  platform: "پلیٹ فارم",
  system: "نظام",
  process: "عمل",
  method: "طریقہ",
  approach: "نقطہ نظر",
  strategy: "حکمت عملی",
  plan: "منصوبہ",
  goal: "مقصد",
  objective: "ہدف",
  target: "ہدف",
  result: "نتیجہ",
  outcome: "نتیجہ",
  impact: "اثر",
  influence: "اثر",
  change: "تبدیلی",
  improvement: "بہتری",
  progress: "پیش قدمی",
  advancement: "ترقی",
  future: "مستقبل",
  potential: "صلاحیت",
  opportunity: "موقع",
  possibility: "امکان",
  capability: "صلاحیت",
  efficiency: "کارکردگی",
  productivity: "پیداوار",
  performance: "کارکردگی",
  effectiveness: "مؤثریت",
  value: "قیمت",
  worth: "قیمت",
  investment: "سرمایہ کاری",
  return: "واپسی",
  profit: "منافع",
  loss: "نقصان",
  risk: "خطرہ",
  security: "سیکیورٹی",
  safety: "تحفظ",
  protection: "تحفظ",
  support: "سپورٹ",
  assistance: "مدد",
  help: "مدد",
  guidance: "رہنمائی",
  advice: "مشورہ",
  recommendation: "تجویز",
  suggestion: "تجویز",
  proposal: "تجویز",
  idea: "آئیڈیا",
  concept: "تصور",
  vision: "وژن",
  mission: "مشن",
  purpose: "مقصد",
  reason: "وجہ",
  cause: "وجہ",
  factor: "عنصر",
  element: "عنصر",
  component: "جزو",
  part: "حصہ",
  section: "سیکشن",
  area: "علاقہ",
  field: "شعبہ",
  industry: "صنعت",
  sector: "شعبہ",
  domain: "ڈومین",
  category: "قسم",
  type: "قسم",
  kind: "قسم",
  sort: "قسم",
  variety: "قسم",
  range: "رینج",
  scope: "دائرہ",
  scale: "پیمانہ",
  size: "سائز",
  amount: "مقدار",
  quantity: "مقدار",
  number: "نمبر",
  count: "گنتی",
  total: "کل",
  sum: "مجموعہ",
  average: "اوسط",
  rate: "شرح",
  percentage: "فیصد",
  ratio: "تناسب",
  proportion: "تناسب",
  comparison: "موازنہ",
  difference: "فرق",
  similarity: "مماثلت",
  relationship: "تعلق",
  connection: "کنکشن",
  link: "لنک",
  association: "تعلق",
  partnership: "شراکت داری",
  collaboration: "تعاون",
  cooperation: "تعاون",
  coordination: "رابطہ",
  integration: "انضمام",
  combination: "امتزاج",
  mixture: "ملاپ",
  blend: "امتزاج",
  fusion: "ملاپ",
  merge: "ملانا",
  unite: "متحد کرنا",
  join: "شامل ہونا",
  connect: "جڑنا",
  attach: "منسلک کرنا",
  bind: "باندھنا",
  tie: "باندھنا",
  link: "لنک کرنا",
  associate: "منسلک کرنا",
  relate: "تعلق رکھنا",
  refer: "حوالہ دینا",
  mention: "ذکر کرنا",
  cite: "حوالہ دینا",
  quote: "اقتباس",
  reference: "حوالہ",
  source: "ذریعہ",
  origin: "اصل",
  basis: "بنیاد",
  foundation: "بنیاد",
  ground: "بنیاد",
  base: "بنیاد",
  root: "جڑ",
  core: "بنیاد",
  heart: "دل",
  center: "مرکز",
  middle: "درمیان",
  focus: "توجہ",
  attention: "توجہ",
  concentration: "توجہ",
  emphasis: "زور",
  importance: "اہمیت",
  significance: "اہمیت",
  relevance: "مطابقت",
  applicability: "قابل اطلاق",
  suitability: "موزوں",
  appropriateness: "مناسب",
  fitness: "موزوں",
  match: "میچ",
  fit: "فٹ",
  suit: "موزوں",
  adapt: "اپنانا",
  adjust: "ایڈجسٹ کرنا",
  modify: "تبدیل کرنا",
  change: "تبدیلی",
  alter: "تبدیل کرنا",
  transform: "تبدیل کرنا",
  convert: "تبدیل کرنا",
  shift: "تبدیل کرنا",
  move: "حرکت",
  motion: "حرکت",
  movement: "حرکت",
  action: "عمل",
  activity: "سرگرمی",
  operation: "آپریشن",
  function: "فنکشن",
  work: "کام",
  job: "نوکری",
  task: "کام",
  duty: "فرض",
  responsibility: "ذمہ داری",
  obligation: "فرض",
  commitment: "عہد",
  promise: "وعدہ",
  guarantee: "گارنٹی",
  assurance: "یقین",
  confidence: "اعتماد",
  trust: "اعتماد",
  faith: "ایمان",
  belief: "یقین",
  conviction: "یقین",
  certainty: "یقین",
  surety: "یقین",
  reliability: "اعتماد",
  dependability: "اعتماد",
  consistency: "مستقل",
  stability: "استحکام",
  steadiness: "استحکام",
  firmness: "مضبوطی",
  strength: "طاقت",
  power: "طاقت",
  force: "طاقت",
  energy: "توانائی",
  vigor: "طاقت",
  vitality: "زندگی",
  life: "زندگی",
  existence: "وجود",
  being: "وجود",
  presence: "موجودگی",
  availability: "دستیابی",
  accessibility: "رسائی",
  reachability: "پہنچ",
  approachability: "قابل رسائی",
  openness: "کھلا پن",
  transparency: "شفافیت",
  clarity: "وضاحت",
  clearness: "صفائی",
  understanding: "سمجھ",
  comprehension: "سمجھ",
  knowledge: "علم",
  wisdom: "حکمت",
  intelligence: "ذہانت",
  smartness: "ذہانت",
  cleverness: "ذہانت",
  brilliance: "ذہانت",
  genius: "ذہین",
  talent: "ٹیلنٹ",
  skill: "مہارت",
  ability: "صلاحیت",
  competence: "صلاحیت",
  expertise: "مہارت",
  mastery: "مہارت",
  proficiency: "مہارت",
  efficiency: "کارکردگی",
  effectiveness: "مؤثریت",
  success: "کامیابی",
  achievement: "کامیابی",
  accomplishment: "کامیابی",
  attainment: "حصول",
  realization: "احساس",
  fulfillment: "تکمیل",
  completion: "تکمیل",
  finish: "ختم",
  end: "اختتام",
  conclusion: "نتیجہ",
  result: "نتیجہ",
  outcome: "نتیجہ",
  consequence: "نتیجہ",
  effect: "اثر",
  impact: "اثر",
  influence: "اثر",
  power: "طاقت",
  control: "کنٹرول",
  command: "کمانڈ",
  authority: "اختیار",
  permission: "اجازت",
  approval: "منظوری",
  acceptance: "قبولیت",
  agreement: "اتفاق",
  consent: "رضامندی",
  confirmation: "تصدیق",
  validation: "توثیق",
  verification: "تصدیق",
  proof: "ثبوت",
  evidence: "ثبوت",
  demonstration: "مظاہرہ",
  illustration: "مثال",
  example: "مثال",
  instance: "مثال",
  case: "کیس",
  situation: "صورتحال",
  condition: "حالت",
  state: "حالت",
  status: "حالت",
  position: "پوزیشن",
  location: "مقام",
  place: "جگہ",
  spot: "جگہ",
  site: "سائٹ",
  venue: "مقام",
  setting: "سیٹنگ",
  environment: "ماحول",
  atmosphere: "ماحول",
  climate: "ماحول",
  weather: "موسم",
  season: "موسم",
  time: "وقت",
  period: "دور",
  era: "دور",
  age: "عمر",
  generation: "نسل",
  phase: "مرحلہ",
  stage: "مرحلہ",
  step: "قدم",
  level: "لیول",
  grade: "درجہ",
  rank: "رینک",
  order: "آرڈر",
  sequence: "تسلسل",
  series: "سیریز",
  chain: "زنجیر",
  line: "لائن",
  row: "قطار",
  column: "کالم",
  list: "فہرست",
  record: "ریکارڈ",
  file: "فائل",
  document: "دستاویز",
  paper: "کاغذ",
  sheet: "شیٹ",
  page: "صفحہ",
  chapter: "باب",
  section: "سیکشن",
  part: "حصہ",
  portion: "حصہ",
  piece: "ٹکڑا",
  segment: "حصہ",
  division: "تقسیم",
  category: "قسم",
  class: "کلاس",
  group: "گروپ",
  set: "سیٹ",
  collection: "مجموعہ",
  assembly: "مجمع",
  gathering: "اجتماع",
  meeting: "میٹنگ",
  conference: "کانفرنس",
  seminar: "سیمینار",
  workshop: "ورکشاپ",
  training: "تربیت",
  education: "تعلیم",
  learning: "سیکھنا",
  study: "مطالعہ",
  research: "تحقیق",
  investigation: "تفتیش",
  examination: "امتحان",
  test: "ٹیسٹ",
  trial: "آزمائش",
  experiment: "تجربہ",
  practice: "مشق",
  exercise: "ورزش",
  drill: "مشق",
  routine: "معمول",
  habit: "عادت",
  custom: "رسم",
  tradition: "روایت",
  culture: "ثقافت",
  civilization: "تہذیب",
  society: "معاشرہ",
  community: "برادری",
  public: "عوام",
  people: "لوگ",
  person: "شخص",
  individual: "فرد",
  human: "انسان",
  man: "آدمی",
  woman: "عورت",
  child: "بچہ",
  family: "خاندان",
  relative: "رشتہ دار",
  friend: "دوست",
  colleague: "ساتھی",
  partner: "شریک",
  associate: "ساتھی",
  companion: "ساتھی",
  member: "رکن",
  participant: "شریک",
  contributor: "شراکت دار",
  supporter: "حامی",
  advocate: "وکیل",
  representative: "نمائندہ",
  agent: "ایجنٹ",
  delegate: "نمائندہ",
  ambassador: "سفیر",
  spokesperson: "ترجمان",
  leader: "رہنما",
  manager: "منیجر",
  director: "ڈائریکٹر",
  executive: "ایگزیکٹو",
  officer: "افسر",
  official: "اہلکار",
  administrator: "منتظم",
  supervisor: "نگران",
  coordinator: "کوآرڈینیٹر",
  organizer: "منتظم",
  planner: "منصوبہ ساز",
  designer: "ڈیزائنر",
  developer: "ڈیولپر",
  creator: "تخلیق کار",
  maker: "بنانے والا",
  builder: "بنانے والا",
  constructor: "تعمیر کنندہ",
  architect: "معمار",
  engineer: "انجینئر",
  technician: "ٹیکنیشن",
  specialist: "ماہر",
  expert: "ماہر",
  professional: "پیشہ ور",
  consultant: "مشیر",
  advisor: "مشیر",
  counselor: "مشیر",
  guide: "رہنما",
  mentor: "استاد",
  teacher: "استاد",
  instructor: "استاد",
  trainer: "ٹرینر",
  coach: "کوچ",
  tutor: "استاد",
  educator: "تعلیم دہندہ",
  scholar: "عالم",
  researcher: "محقق",
  scientist: "سائنسدان",
  analyst: "تجزیہ کار",
  reviewer: "جائزہ کار",
  critic: "نقاد",
  evaluator: "جانچنے والا",
  assessor: "جانچنے والا",
  judge: "جج",
  referee: "ریفری",
  mediator: "ثالث",
  arbitrator: "ثالث",
  negotiator: "مذاکرہ کار",
  diplomat: "سفارتکار",
  politician: "سیاستدان",
  statesman: "سیاستدان",
  citizen: "شہری",
  resident: "رہائشی",
  inhabitant: "باشندہ",
  native: "مقامی",
  local: "مقامی",
  national: "قومی",
  international: "بین الاقوامی",
  global: "عالمی",
  worldwide: "دنیا بھر میں",
  universal: "آفاقی",
  general: "عام",
  common: "عام",
  ordinary: "عام",
  normal: "عام",
  regular: "باقاعدہ",
  standard: "معیار",
  typical: "عام",
  usual: "عام",
  traditional: "روایتی",
  conventional: "روایتی",
  classic: "کلاسک",
  original: "اصل",
  authentic: "اصل",
  genuine: "اصل",
  real: "حقیقی",
  true: "سچ",
  actual: "اصل",
  factual: "حقیقی",
  accurate: "درست",
  correct: "درست",
  right: "درست",
  proper: "مناسب",
  appropriate: "مناسب",
  suitable: "موزوں",
  fitting: "مناسب",
  relevant: "متعلقہ",
  applicable: "قابل اطلاق",
  useful: "مفید",
  helpful: "مددگار",
  beneficial: "فائدہ مند",
  advantageous: "فائدہ مند",
  profitable: "منافع بخش",
  valuable: "قیمتی",
  precious: "قیمتی",
  important: "اہم",
  significant: "اہم",
  major: "اہم",
  minor: "معمولی",
  small: "چھوٹا",
  little: "تھوڑا",
  tiny: "چھوٹا",
  huge: "بہت بڑا",
  large: "بڑا",
  big: "بڑا",
  great: "عظیم",
  excellent: "بہترین",
  outstanding: "شاندار",
  remarkable: "قابل ذکر",
  notable: "قابل ذکر",
  significant: "اہم",
  considerable: "قابل اعتبار",
  substantial: "خاطر خواہ",
  extensive: "وسیع",
  comprehensive: "جامع",
  complete: "مکمل",
  full: "مکمل",
  entire: "تمام",
  whole: "تمام",
  total: "کل",
  overall: "مجموعی",
  general: "عام",
  specific: "مخصوص",
  particular: "خاص",
  special: "خاص",
  unique: "منفرد",
  distinct: "الگ",
  different: "مختلف",
  various: "مختلف",
  diverse: "متنوع",
  multiple: "متعدد",
  several: "کئی",
  many: "بہت سے",
  numerous: "بہت سے",
  countless: "بے شمار",
  infinite: "لامحدود",
  unlimited: "لامحدود",
  boundless: "لامحدود",
  endless: "لامتناہی",
  eternal: "ابدی",
  permanent: "مستقل",
  lasting: "دیرپا",
  durable: "پائیدار",
  stable: "مستحکم",
  solid: "مضبوط",
  strong: "مضبوط",
  powerful: "طاقتور",
  effective: "مؤثر",
  efficient: "کارآمد",
  productive: "پیداواری",
  successful: "کامیاب",
  victorious: "کامیاب",
  winning: "جیتنے والا",
  triumphant: "کامیاب",
  champion: "چیمپین",
  winner: "جیتنے والا",
  leader: "رہنما",
  first: "پہلا",
  top: "اوپر",
  best: "بہترین",
  finest: "بہترین",
  greatest: "سب سے بڑا",
  highest: "سب سے اونچا",
  maximum: "زیادہ سے زیادہ",
  minimum: "کم سے کم",
  lowest: "سب سے کم",
  smallest: "سب سے چھوٹا",
  shortest: "سب سے چھوٹا",
  longest: "سب سے لمبا",
  fastest: "سب سے تیز",
  slowest: "سب سے آہستہ",
  newest: "سب سے نیا",
  oldest: "سب سے پرانا",
  latest: "جدید ترین",
  recent: "حالیہ",
  current: "موجودہ",
  present: "موجودہ",
  existing: "موجودہ",
  available: "دستیاب",
  accessible: "قابل رسائی",
  obtainable: "حاصل کرنے کے قابل",
  achievable: "قابل حصول",
  possible: "ممکن",
  feasible: "عملی",
  practical: "عملی",
  realistic: "حقیقت پسندانہ",
  reasonable: "معقول",
  logical: "منطقی",
  sensible: "سمجھدار",
  wise: "دانشمند",
  smart: "ذہین",
  intelligent: "ذہین",
  clever: "ہوشیار",
  brilliant: "شاندار",
  creative: "تخلیقی",
  innovative: "جدید",
  modern: "جدید",
  contemporary: "عصری",
  advanced: "ترقی یافتہ",
  sophisticated: "نفیس",
  complex: "پیچیدہ",
  complicated: "پیچیدہ",
  difficult: "مشکل",
  hard: "سخت",
  tough: "سخت",
  challenging: "چیلنجنگ",
  demanding: "مطالبہ کرنے والا",
  requiring: "ضرورت",
  needing: "ضرورت",
  wanting: "چاہنا",
  desiring: "خواہش",
  wishing: "خواہش",
  hoping: "امید",
  expecting: "توقع",
  anticipating: "توقع",
  predicting: "پیش گوئی",
  forecasting: "پیش گوئی",
  planning: "منصوبہ بندی",
  preparing: "تیاری",
  organizing: "منظم کرنا",
  arranging: "انتظام",
  coordinating: "رابطہ",
  managing: "انتظام",
  controlling: "کنٹرول",
  directing: "ہدایت",
  leading: "قیادت",
  guiding: "رہنمائی",
  instructing: "ہدایت",
  teaching: "تدریس",
  training: "تربیت",
  coaching: "کوچنگ",
  mentoring: "رہنمائی",
  advising: "مشورہ",
  consulting: "مشاورت",
  counseling: "مشاورت",
  supporting: "سپورٹ",
  helping: "مدد",
  assisting: "معاونت",
  aiding: "مدد",
  facilitating: "آسان بنانا",
  enabling: "قابل بنانا",
  empowering: "بااختیار بنانا",
  strengthening: "مضبوط بنانا",
  improving: "بہتری",
  enhancing: "بہتری",
  upgrading: "اپگریڈ",
  updating: "اپڈیٹ",
  modernizing: "جدید بنانا",
  revolutionizing: "انقلاب",
  transforming: "تبدیل کرنا",
  changing: "تبدیل کرنا",
  modifying: "تبدیل کرنا",
  adjusting: "ایڈجسٹ کرنا",
  adapting: "ڈھالنا",
  customizing: "حسب ضرورت",
  personalizing: "ذاتی بنانا",
  individualizing: "انفرادی بنانا",
  specializing: "مہارت حاصل کرنا",
  focusing: "توجہ مرکوز کرنا",
  concentrating: "توجہ مرکوز کرنا",
  targeting: "ہدف بنانا",
  aiming: "نشانہ لگانا",
  striving: "کوشش کرنا",
  trying: "کوشش کرنا",
  attempting: "کوشش کرنا",
  endeavoring: "کوشش کرنا",
  working: "کام کرنا",
  operating: "چلانا",
  functioning: "کام کرنا",
  performing: "کارکردگی",
  executing: "عمل کرنا",
  implementing: "نافذ کرنا",
  applying: "لاگو کرنا",
  using: "استعمال کرنا",
  utilizing: "استعمال کرنا",
  employing: "استعمال کرنا",
  deploying: "تعینات کرنا",
  installing: "انسٹال کرنا",
  setting: "سیٹ کرنا",
  establishing: "قائم کرنا",
  creating: "بنانا",
  building: "تعمیر کرنا",
  constructing: "تعمیر کرنا",
  developing: "ترقی کرنا",
  designing: "ڈیزائن کرنا",
  crafting: "بنانا",
  manufacturing: "تیار کرنا",
  producing: "پیدا کرنا",
  generating: "پیدا کرنا",
  creating: "تخلیق کرنا",
  innovating: "جدت طرازی",
  inventing: "ایجاد کرنا",
  discovering: "دریافت کرنا",
  finding: "تلاش کرنا",
  searching: "تلاش کرنا",
  looking: "دیکھنا",
  seeking: "تلاش کرنا",
  exploring: "کھوج کرنا",
  investigating: "تحقیق کرنا",
  researching: "تحقیق کرنا",
  studying: "مطالعہ کرنا",
  analyzing: "تجزیہ کرنا",
  examining: "جانچنا",
  reviewing: "جائزہ لینا",
  evaluating: "جانچنا",
  assessing: "اندازہ لگانا",
  measuring: "پیمائش کرنا",
  calculating: "حساب لگانا",
  computing: "کمپیوٹنگ",
  processing: "پروسیسنگ",
  handling: "سنبھالنا",
  dealing: "نمٹنا",
  managing: "منظوری",
  organizing: "منظم کرنا",
  structuring: "ڈھانچہ بنانا",
  formatting: "فارمیٹ کرنا",
  styling: "اسٹائل کرنا",
  designing: "ڈیزائن کرنا",
  decorating: "سجانا",
  beautifying: "خوبصورت بنانا",
  enhancing: "بہتر بنانا",
  optimizing: "بہتر بنانا",
  maximizing: "زیادہ سے زیادہ",
  minimizing: "کم سے کم",
  reducing: "کم کرنا",
  decreasing: "کم کرنا",
  lowering: "کم کرنا",
  cutting: "کاٹنا",
  trimming: "کاٹنا",
  shortening: "چھوٹا کرنا",
  compressing: "دبانا",
  condensing: "گاڑھا کرنا",
  summarizing: "خلاصہ کرنا",
  simplifying: "آسان بنانا",
  clarifying: "واضح کرنا",
  explaining: "وضاحت کرنا",
  describing: "بیان کرنا",
  defining: "تعین کرنا",
  specifying: "مخصوص کرنا",
  detailing: "تفصیل دینا",
  elaborating: "تفصیل سے بیان کرنا",
  expanding: "پھیلانا",
  extending: "بڑھانا",
  increasing: "بڑھانا",
  growing: "بڑھنا",
  developing: "ترقی کرنا",
  progressing: "پیش قدمی",
  advancing: "ترقی کرنا",
  moving: "حرکت کرنا",
  proceeding: "آگے بڑھنا",
  continuing: "جاری رکھنا",
  maintaining: "برقرار رکھنا",
  sustaining: "برقرار رکھنا",
  preserving: "محفوظ رکھنا",
  protecting: "محفوظ رکھنا",
  securing: "محفوظ کرنا",
  safeguarding: "محفوظ رکھنا",
  ensuring: "یقینی بنانا",
  guaranteeing: "ضمانت دینا",
  promising: "وعدہ کرنا",
  committing: "عہد کرنا",
  dedicating: "وقف کرنا",
  devoting: "وقف کرنا",
  investing: "سرمایہ کاری",
  spending: "خرچ کرنا",
  allocating: "تفویض کرنا",
  distributing: "تقسیم کرنا",
  sharing: "بانٹنا",
  dividing: "تقسیم کرنا",
  splitting: "تقسیم کرنا",
  separating: "الگ کرنا",
  isolating: "الگ کرنا",
  distinguishing: "فرق کرنا",
  differentiating: "فرق کرنا",
  comparing: "موازنہ کرنا",
  contrasting: "موازنہ کرنا",
  relating: "تعلق جوڑنا",
  connecting: "جوڑنا",
  linking: "لنک کرنا",
  joining: "شامل ہونا",
  combining: "ملانا",
  integrating: "شامل کرنا",
  merging: "ضم کرنا",
  uniting: "متحد کرنا",
  consolidating: "مضبوط بنانا",
  strengthening: "مضبوط کرنا",
  reinforcing: "تقویت دینا",
  supporting: "مدد کرنا",
  backing: "حمایت کرنا",
  endorsing: "حمایت کرنا",
  approving: "منظوری دینا",
  accepting: "قبول کرنا",
  agreeing: "اتفاق کرنا",
  consenting: "رضامندی دینا",
  permitting: "اجازت دینا",
  allowing: "اجازت دینا",
  enabling: "قابل بنانا",
  facilitating: "آسان بنانا",
  simplifying: "آسان بنانا",
  streamlining: "آسان بنانا",
  automating: "خودکار بنانا",
  mechanizing: "مکینیکل بنانا",
  digitalizing: "ڈیجیٹل بنانا",
  computerizing: "کمپیوٹرائز کرنا",
  technologizing: "ٹیکنالوجی کا استعمال",
  innovating: "جدت طرازی کرنا",
  modernizing: "جدید بنانا",
  updating: "اپڈیٹ کرنا",
  upgrading: "اپگریڈ کرنا",
  improving: "بہتری کرنا",
  bettering: "بہتر بنانا",
  perfecting: "کامل بنانا",
  refining: "بہتر بنانا",
  polishing: "چمکانا",
  finishing: "مکمل کرنا",
  completing: "تکمیل کرنا",
  concluding: "اختتام کرنا",
  ending: "ختم کرنا",
  closing: "بند کرنا",
  finalizing: "حتمی شکل دینا",
  accomplishing: "مکمل کرنا",
  achieving: "حاصل کرنا",
  attaining: "حاصل کرنا",
  reaching: "پہنچنا",
  obtaining: "حاصل کرنا",
  acquiring: "حاصل کرنا",
  gaining: "حاصل کرنا",
  earning: "کمانا",
  winning: "جیتنا",
  securing: "محفوظ کرنا",
  capturing: "قبضہ کرنا",
  seizing: "قبضہ کرنا",
  grasping: "پکڑنا",
  holding: "پکڑنا",
  maintaining: "برقرار رکھنا",
  keeping: "رکھنا",
  retaining: "برقرار رکھنا",
  preserving: "محفوظ رکھنا",
  conserving: "محفوظ رکھنا",
  saving: "بچانا",
  storing: "محفوظ کرنا",
  archiving: "محفوظ کرنا",
  recording: "ریکارڈ کرنا",
  documenting: "دستاویز بنانا",
  noting: "نوٹ کرنا",
  writing: "لکھنا",
  typing: "ٹائپ کرنا",
  printing: "پرنٹ کرنا",
  publishing: "شائع کرنا",
  releasing: "جاری کرنا",
  launching: "شروع کرنا",
  introducing: "متعارف کرانا",
  presenting: "پیش کرنا",
  showing: "دکھانا",
  displaying: "دکھانا",
  exhibiting: "نمائش کرنا",
  demonstrating: "مظاہرہ کرنا",
  illustrating: "واضح کرنا",
  visualizing: "تصور کرنا",
  imagining: "تصور کرنا",
  picturing: "تصویر بنانا",
  envisioning: "تصور کرنا",
  conceiving: "تصور کرنا",
  thinking: "سوچنا",
  considering: "غور کرنا",
  pondering: "سوچنا",
  reflecting: "غور کرنا",
  contemplating: "غور کرنا",
  meditating: "تامل کرنا",
  concentrating: "توجہ مرکوز کرنا",
  focusing: "توجہ مرکوز کرنا",
  attending: "توجہ دینا",
  listening: "سننا",
  hearing: "سننا",
  observing: "مشاہدہ کرنا",
  watching: "دیکھنا",
  viewing: "دیکھنا",
  seeing: "دیکھنا",
  looking: "دیکھنا",
  gazing: "نظر کرنا",
  staring: "گھورنا",
  glancing: "جھلک دیکھنا",
  peeking: "جھانکنا",
  glimpsing: "جھلک دیکھنا",
  spotting: "دیکھنا",
  noticing: "نوٹس کرنا",
  recognizing: "پہچاننا",
  identifying: "شناخت کرنا",
  distinguishing: "فرق کرنا",
  discerning: "پہچاننا",
  perceiving: "سمجھنا",
  understanding: "سمجھنا",
  comprehending: "سمجھنا",
  grasping: "سمجھنا",
  realizing: "احساس کرنا",
  recognizing: "تسلیم کرنا",
  acknowledging: "تسلیم کرنا",
  admitting: "تسلیم کرنا",
  confessing: "اعتراف کرنا",
  declaring: "اعلان کرنا",
  announcing: "اعلان کرنا",
  proclaiming: "اعلان کرنا",
  stating: "بیان کرنا",
  saying: "کہنا",
  telling: "بتانا",
  speaking: "بولنا",
  talking: "بات کرنا",
  communicating: "بات چیت کرنا",
  conversing: "گفتگو کرنا",
  discussing: "بحث کرنا",
  debating: "بحث کرنا",
  arguing: "بحث کرنا",
  negotiating: "مذاکرہ کرنا",
  bargaining: "سودا بازی کرنا",
  dealing: "معاملہ کرنا",
  trading: "تجارت کرنا",
  exchanging: "تبادلہ کرنا",
  swapping: "تبادلہ کرنا",
  switching: "تبدیل کرنا",
  changing: "تبدیل کرنا",
  altering: "تبدیل کرنا",
  modifying: "تبدیل کرنا",
  adjusting: "ایڈجسٹ کرنا",
  adapting: "ڈھالنا",
  transforming: "تبدیل کرنا",
  converting: "تبدیل کرنا",
  translating: "ترجمہ کرنا",
  interpreting: "تشریح کرنا",
  explaining: "وضاحت کرنا",
  clarifying: "واضح کرنا",
  company: "کمپنی",
  market: "بازار",
  product: "پروڈکٹ",
  service: "سروس",
  customer: "کسٹمر",
  management: "انتظام",
  project: "پروجیکٹ",
  team: "ٹیم",
  work: "کام",
  job: "نوکری",
  career: "کیریئر",
  skill: "مہارت",
  knowledge: "علم",
  education: "تعلیم",
  training: "تربیت",
  course: "کورس",
  study: "مطالعہ",
  research: "تحقیق",
  analysis: "تجزیہ",
  report: "رپورٹ",
  information: "معلومات",
  strategy: "حکمت عملی",
  financial: "مالی",
  marketers: "مارکیٹرز",
  institute: "ادارہ",
  states: "بتاتا ہے",
  about: "تقریباً",
  using: "استعمال کر رہے ہیں",
  rut: "خرابی میں",
  marketing: "مارکیٹنگ",
  revenue: "آمدنی",
  growth: "ترقی",
  audience: "سامعین",
  engagement: "مشغولیت",
  analytics: "تجزیات",
  performance: "کارکردگی",
  conversion: "تبدیلی",
  optimization: "بہتری",
  campaign: "مہم",
  advertising: "اشتہارات",
  promotion: "فروغ",
  innovation: "جدت",
  solution: "حل",
  trends: "رجحانات",
  insights: "بصیرت",
  statistics: "اعداد و شمار",
  success: "کامیابی",
  challenges: "چیلنجز",
  opportunities: "مواقع",
  benefits: "فوائد",
  advantages: "فوائد",
  features: "خصوصیات",
  quality: "معیار",
  professional: "پیشہ ور",
  expert: "ماہر",
  leadership: "قیادت",
  collaboration: "تعاون",
  communication: "رابطہ",
  platform: "پلیٹ فارم",
  process: "عمل",
  method: "طریقہ",
  approach: "نقطہ نظر",
  plan: "منصوبہ",
  goal: "مقصد",
  objective: "ہدف",
  target: "ہدف",
  result: "نتیجہ",
  outcome: "نتیجہ",
  impact: "اثر",
  influence: "اثر",
  change: "تبدیلی",
  improvement: "بہتری",
  progress: "پیش قدمی",
  advancement: "ترقی",
  future: "مستقبل",
  potential: "صلاحیت",
  opportunity: "موقع",
  possibility: "امکان",
  capability: "صلاحیت",
  efficiency: "کارکردگی",
  productivity: "پیداوار",
  effectiveness: "مؤثریت",
  value: "قیمت",
  worth: "قیمت",
  investment: "سرمایہ کاری",
  return: "واپسی",
  profit: "منافع",
  loss: "نقصان",
  risk: "خطرہ",
  safety: "تحفظ",
  protection: "تحفظ",
  support: "سپورٹ",
  assistance: "مدد",
  help: "مدد",
  guidance: "رہنمائی",
  advice: "مشورہ",
  recommendation: "تجویز",
  suggestion: "تجویز",
  proposal: "تجویز",
  idea: "آئیڈیا",
  concept: "تصور",
  vision: "وژن",
  mission: "مشن",
  purpose: "مقصد",

  // Additional comprehensive terms
  news: "خبریں",
  article: "مضمون",
  blog: "بلاگ",
  post: "پوسٹ",
  content: "مواد",
  text: "متن",
  message: "پیغام",
  email: "ای میل",
  media: "میڈیا",
  account: "اکاؤنٹ",
  profile: "پروفائل",
  setting: "سیٹنگ",
  option: "آپشن",
  feature: "خصوصیت",
  function: "فنکشن",
  tool: "ٹول",
  resource: "وسائل",
  problem: "مسئلہ",
  issue: "مسئلہ",
  error: "خرابی",
  bug: "بگ",
  fix: "ٹھیک کرنا",
  update: "اپ ڈیٹ",
  upgrade: "اپ گریڈ",
  install: "انسٹال",
  download: "ڈاؤن لوڈ",
  upload: "اپ لوڈ",
  save: "محفوظ کرنا",
  delete: "ڈیلیٹ",
  remove: "ہٹانا",
  add: "شامل کرنا",
  create: "بنانا",
  build: "بنانا",
  make: "بنانا",
  do: "کرنا",
  get: "حاصل کرنا",
  take: "لینا",
  give: "دینا",
  put: "رکھنا",
  go: "جانا",
  come: "آنا",
  see: "دیکھنا",
  look: "دیکھنا",
  find: "تلاش کرنا",
  search: "تلاش",
  contact: "رابطہ",
  home: "گھر",
  page: "صفحہ",
  site: "سائٹ",
  link: "لنک",
  click: "کلک",
  button: "بٹن",
  menu: "مینو",
  list: "فہرست",
  item: "آئٹم",
  category: "کیٹگری",
  type: "قسم",
  kind: "قسم",
  way: "طریقہ",
  step: "قدم",
  stage: "مرحلہ",
  phase: "مرحلہ",
  level: "سطح",
  degree: "درجہ",
  standard: "معیار",
  failure: "ناکامی",
  win: "جیت",
  lose: "ہار",
  good: "اچھا",
  bad: "برا",
  best: "بہترین",
  better: "بہتر",
  new: "نیا",
  old: "پرانا",
  big: "بڑا",
  small: "چھوٹا",
  large: "بڑا",
  little: "چھوٹا",
  high: "اونچا",
  low: "نیچا",
  long: "لمبا",
  short: "چھوٹا",
  fast: "تیز",
  slow: "آہستہ",
  easy: "آسان",
  hard: "مشکل",
  difficult: "مشکل",
  simple: "آسان",
  complex: "پیچیدہ",
  important: "اہم",
  necessary: "ضروری",
  useful: "مفید",
  effective: "مؤثر",
  efficient: "موثر",
  popular: "مقبول",
  common: "عام",
  special: "خاص",
  unique: "منفرد",
  different: "مختلف",
  same: "ویسا ہی",
  similar: "ملتا جلتا",
  possible: "ممکن",
  available: "دستیاب",
  free: "مفت",
  open: "کھلا",
  close: "بند",
  start: "شروع",
  begin: "شروع کرنا",
  end: "ختم",
  finish: "ختم کرنا",
  complete: "مکمل",
  ready: "تیار",
  done: "ہو گیا",
  working: "کام کر رہا",
  running: "چل رہا",
  active: "فعال",
  inactive: "غیر فعال",
  connected: "جڑا ہوا",
  disconnected: "منقطع",
  secure: "محفوظ",
  safe: "محفوظ",
  private: "نجی",
  public: "عوامی",
  personal: "ذاتی",
  technical: "تکنیکی",
  scientific: "سائنسی",
  medical: "طبی",
  legal: "قانونی",
  economic: "اقتصادی",
  educational: "تعلیمی",
  academic: "تعلیمی",
  creativity: "تخلیقیت",
  art: "فن",
  music: "موسیقی",
  video: "ویڈیو",
  audio: "آڈیو",
  image: "تصویر",
  photo: "تصویر",
  picture: "تصویر",
  file: "فائل",
  document: "دستاویز",
  folder: "فولڈر",
  directory: "ڈائریکٹری",
  path: "راستہ",
  location: "مقام",
  address: "پتہ",
  url: "یو آر ایل",
  connection: "کنکشن",
  server: "سرور",
  client: "کلائنٹ",
  host: "ہوسٹ",
  domain: "ڈومین",
  protocol: "پروٹوکول",
  http: "ایچ ٹی ٹی پی",
  https: "ایچ ٹی ٹی پی ایس",
  api: "اے پی آئی",
  query: "کوئری",
  filter: "فلٹر",
  sort: "ترتیب",
  order: "ترتیب",
  group: "گروپ",
  tag: "ٹیگ",
  label: "لیبل",
  title: "عنوان",
  name: "نام",
  description: "تفصیل",
  summary: "خلاصہ",
  overview: "جائزہ",
  introduction: "تعارف",
  conclusion: "نتیجہ",
  comment: "تبصرہ",
  feedback: "رائے",
  review: "جائزہ",
  rating: "درجہ بندی",
  score: "اسکور",
  point: "نکتہ",
  mark: "نشان",
  sign: "نشان",
  symbol: "علامت",
  icon: "آئیکن",
  logo: "لوگو",
  brand: "برانڈ",
  organization: "تنظیم",
  institution: "ادارہ",
  agency: "ایجنسی",
  department: "شعبہ",
  division: "ڈویژن",
  section: "سیکشن",
  unit: "یونٹ",
  member: "رکن",
  staff: "عملہ",
  employee: "ملازم",
  worker: "کارکن",
  manager: "منیجر",
  director: "ڈائریکٹر",
  executive: "ایگزیکٹو",
  administrator: "ایڈمنسٹریٹر",
  supervisor: "نگران",
  coordinator: "کوآرڈینیٹر",
  specialist: "ماہر",
  consultant: "مشیر",
  advisor: "مشیر",
  analyst: "تجزیہ کار",
  developer: "ڈیولپر",
  programmer: "پروگرامر",
  engineer: "انجینئر",
  designer: "ڈیزائنر",
  architect: "آرکیٹیکٹ",
  scientist: "سائنس دان",
  researcher: "محقق",
  student: "طالب علم",
  teacher: "استاد",
  professor: "پروفیسر",
  instructor: "انسٹرکٹر",
  trainer: "ٹرینر",
  coach: "کوچ",
  mentor: "رہنما",
  guide: "گائیڈ",
  leader: "رہنما",
  assistant: "اسسٹنٹ",
  helper: "مددگار",
  supporter: "حامی",
  partner: "شریک",
  colleague: "ساتھی",
  friend: "دوست",
  family: "خاندان",
  community: "کمیونٹی",
  society: "معاشرہ",
  world: "دنیا",
  country: "ملک",
  nation: "قوم",
  state: "ریاست",
  city: "شہر",
  town: "شہر",
  village: "گاؤں",
  area: "علاقہ",
  region: "خطہ",
  zone: "زون",
  place: "جگہ",
  space: "جگہ",
  room: "کمرہ",
  office: "دفتر",
  building: "عمارت",
  house: "گھر",
  center: "مرکز",
  facility: "سہولت",
  equipment: "سامان",
  device: "آلہ",
  instrument: "آلہ",
  hardware: "ہارڈ ویئر",
  program: "پروگرام",
  framework: "فریم ورک",
  library: "لائبریری",
  module: "ماڈیول",
  component: "جزو",
  element: "عنصر",
  part: "حصہ",
  piece: "ٹکڑا",
  chapter: "باب",
  lesson: "سبق",
  class: "کلاس",
  subject: "مضمون",
  topic: "موضوع",
  theme: "موضوع",
  thought: "سوچ",
  opinion: "رائے",
  view: "نظریہ",
  perspective: "نقطہ نظر",
  aim: "مقصد",
  reason: "وجہ",
  cause: "سبب",
  effect: "اثر",
  increase: "اضافہ",
  decrease: "کمی",
  reduction: "کمی",
  expansion: "توسیع",
  extension: "توسیع",
  enhancement: "بہتری",
  speed: "رفتار",
  reliability: "اعتماد",
  stability: "استحکام",
  privacy: "نجی زندگی",
  confidentiality: "رازداری",
};

/**
 * Enhanced translation function with improved context handling
 * @param {string} text - Text to translate from English to Urdu
 * @returns {string} - Translated text in Urdu
 */
export function translateToUrdu(text) {
  if (!text) return "";

  let translatedText = text.toLowerCase();

  // Sort by length (longest first) to avoid partial replacements
  const sortedTranslations = Object.entries(englishToUrdu).sort(
    ([a], [b]) => b.length - a.length
  );

  // Apply translations with proper word boundary matching
  sortedTranslations.forEach(([english, urdu]) => {
    const regex = new RegExp(
      `\\b${english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`,
      "gi"
    );
    translatedText = translatedText.replace(regex, urdu);
  });

  // Apply enhanced grammar fixes for better Urdu text flow
  translatedText = translatedText
    .replace(/\s+/g, " ") // Remove extra spaces
    .replace(/(\d+)\s*فیصد/g, "$1 فیصد") // Fix percentage formatting
    .replace(/کے\s+بارے\s+میں/g, "کے بارے میں") // Fix "about" phrase
    .replace(/استعمال\s+کر\s+رہے\s+ہیں/g, "استعمال کر رہے ہیں") // Fix "using" phrase
    .replace(/مواد\s+کی\s+مارکیٹنگ/g, "مواد کی مارکیٹنگ") // Fix content marketing
    .replace(/سوشل\s+میڈیا/g, "سوشل میڈیا") // Fix social media
    .replace(/مصنوعی\s+ذہانت/g, "مصنوعی ذہانت") // Fix artificial intelligence
    .replace(/کمپنی\s+کا/g, "کمپنی کا") // Fix company possessive
    .replace(/کاروبار\s+کی/g, "کاروبار کی") // Fix business possessive
    .replace(/ٹیکنالوجی\s+کا/g, "ٹیکنالوجی کا") // Fix technology possessive
    .replace(/انٹرنیٹ\s+پر/g, "انٹرنیٹ پر") // Fix "on internet"
    .replace(/ویب\s+سائٹ/g, "ویب سائٹ") // Fix website spacing
    .replace(/ای\s+میل/g, "ای میل") // Fix email spacing
    .replace(/آن\s+لائن/g, "آن لائن") // Fix online spacing
    .replace(/ڈیٹا\s+بیس/g, "ڈیٹابیس") // Fix database spacing
    .replace(/سافٹ\s+ویئر/g, "سافٹ ویئر") // Fix software spacing
    .replace(/ہارڈ\s+ویئر/g, "ہارڈ ویئر") // Fix hardware spacing
    .replace(/نیٹ\s+ورک/g, "نیٹ ورک") // Fix network spacing
    .replace(/یو\s+آر\s+ایل/g, "یو آر ایل") // Fix URL spacing
    .replace(/اے\s+پی\s+آئی/g, "اے پی آئی") // Fix API spacing
    .trim();

  return translatedText;
}

/**
 * Enhanced translation function with sentence-level processing
 * @param {string} text - Text to translate from English to Urdu
 * @returns {string} - Translated text in Urdu with proper sentence structure
 */
export function translateToUrduAdvanced(text) {
  if (!text) return "";

  // Split text into sentences for better context handling
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);

  const translatedSentences = sentences.map((sentence) => {
    // Clean and translate each sentence
    let cleanSentence = sentence.trim();
    let translatedSentence = translateToUrdu(cleanSentence);

    // Apply sentence-level grammar improvements
    translatedSentence = applySentenceGrammarFixes(translatedSentence);

    return translatedSentence;
  });

  // Join sentences with proper Urdu punctuation
  let result = translatedSentences.join("۔ ");
  if (result && !result.endsWith("۔")) {
    result += "۔";
  }

  return result;
}

/**
 * Apply sentence-level grammar fixes for better Urdu flow
 * @param {string} sentence - Single sentence to fix
 * @returns {string} - Grammar-corrected sentence
 */
function applySentenceGrammarFixes(sentence) {
  return (
    sentence
      // Fix common verb conjugations
      .replace(/ہے\s+استعمال/g, "استعمال کر رہے ہیں")
      .replace(/ہے\s+کام/g, "کام کر رہا ہے")
      .replace(/ہے\s+بڑھ/g, "بڑھ رہا ہے")
      .replace(/ہے\s+آ/g, "آ رہا ہے")
      .replace(/ہے\s+جا/g, "جا رہا ہے")

      // Fix possessive constructions
      .replace(/(\w+)\s+کا\s+(\w+)/g, "$1 کا $2")
      .replace(/(\w+)\s+کی\s+(\w+)/g, "$1 کی $2")
      .replace(/(\w+)\s+کے\s+(\w+)/g, "$1 کے $2")

      // Fix preposition usage
      .replace(/میں\s+سے/g, "میں سے")
      .replace(/کے\s+ساتھ/g, "کے ساتھ")
      .replace(/کے\s+لیے/g, "کے لیے")
      .replace(/کے\s+ذریعے/g, "کے ذریعے")

      // Fix compound terms
      .replace(/تقریباً\s+(\d+)/g, "تقریباً $1")
      .replace(/(\d+)\s+سال/g, "$1 سال")
      .replace(/(\d+)\s+مہینے/g, "$1 مہینے")
      .replace(/(\d+)\s+دن/g, "$1 دن")

      // Capitalize first letter after fixing
      .replace(/^(\w)/, (match, p1) => p1.toUpperCase())
  );
}

/**
 * Generate a comprehensive summary with enhanced translation
 * @param {string} text - Original English text
 * @returns {Object} - Object containing both English and Urdu summaries with metadata
 */
export function generateBilingualSummary(text) {
  if (!text) return null;

  // Generate English summary (simplified version)
  const englishSummary = generateEnglishSummary(text);

  // Translate to Urdu with advanced processing
  const urduSummary = translateToUrduAdvanced(englishSummary);

  // Extract keywords from original text
  const keywords = extractKeywords(text);

  // Calculate metadata
  const wordCount = englishSummary.split(/\s+/).length;
  const readingTime = Math.ceil(wordCount / 200); // Average reading speed

  return {
    english: englishSummary,
    urdu: urduSummary,
    keywords: keywords,
    metadata: {
      wordCount,
      readingTime,
      originalLength: text.split(/\s+/).length,
      compressionRatio: Math.round(
        (wordCount / text.split(/\s+/).length) * 100
      ),
    },
  };
}

/**
 * Generate English summary from text (simplified algorithm)
 * @param {string} text - Original text to summarize
 * @returns {string} - Generated summary
 */
function generateEnglishSummary(text) {
  // Split into sentences
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 20);

  // Score sentences based on importance indicators
  const scoredSentences = sentences.map((sentence) => {
    let score = 0;

    // Higher score for sentences with numbers/statistics
    if (/\d+%|\d+ percent/i.test(sentence)) score += 3;
    if (/\d/.test(sentence)) score += 1;

    // Higher score for sentences with important keywords
    const importantWords = [
      "according to",
      "research shows",
      "study finds",
      "key",
      "important",
      "significant",
      "main",
      "primary",
      "major",
      "critical",
      "essential",
    ];
    importantWords.forEach((word) => {
      if (sentence.toLowerCase().includes(word)) score += 2;
    });

    // Higher score for sentences mentioning business concepts
    const businessWords = [
      "marketing",
      "business",
      "company",
      "strategy",
      "growth",
      "revenue",
      "profit",
      "customer",
      "market",
      "sales",
    ];
    businessWords.forEach((word) => {
      if (sentence.toLowerCase().includes(word)) score += 1;
    });

    // Prefer sentences at beginning and end
    const index = sentences.indexOf(sentence);
    if (index < 2 || index > sentences.length - 3) score += 1;

    return { sentence: sentence.trim(), score };
  });

  // Select top-scoring sentences
  const topSentences = scoredSentences
    .sort((a, b) => b.score - a.score)
    .slice(0, Math.min(4, Math.ceil(sentences.length * 0.3)))
    .map((item) => item.sentence);

  // Create coherent summary
  let summary = topSentences.join(". ");
  if (!summary.endsWith(".")) summary += ".";

  return summary;
}

/**
 * Extract relevant keywords from text
 * @param {string} text - Text to extract keywords from
 * @returns {Array} - Array of relevant keywords
 */
function extractKeywords(text) {
  // Convert to lowercase and extract words
  const words = text
    .toLowerCase()
    .replace(/[^\w\s]/g, " ")
    .split(/\s+/)
    .filter((word) => word.length > 3);

  // Common stop words to filter out
  const stopWords = new Set([
    "this",
    "that",
    "with",
    "from",
    "they",
    "have",
    "been",
    "will",
    "some",
    "more",
    "what",
    "time",
    "very",
    "when",
    "much",
    "many",
    "most",
    "such",
    "like",
    "into",
    "than",
    "only",
    "other",
    "also",
    "just",
    "well",
    "over",
    "back",
    "even",
    "make",
    "take",
    "know",
    "think",
    "come",
    "could",
    "would",
    "should",
    "might",
    "must",
    "need",
    "want",
    "work",
    "part",
    "place",
    "right",
    "great",
    "where",
    "while",
    "still",
    "being",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "among",
    "within",
    "without",
    "against",
    "about",
    "around",
    "under",
  ]);

  // Count word frequencies
  const wordFreq = {};
  words.forEach((word) => {
    if (!stopWords.has(word) && word.length > 3) {
      wordFreq[word] = (wordFreq[word] || 0) + 1;
    }
  });

  // Return top keywords
  return Object.entries(wordFreq)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 8)
    .map(([word]) => word);
}

/**
 * Get translation statistics and metadata
 * @returns {Object} - Translation system statistics
 */
export function getTranslationStats() {
  return {
    dictionarySize: Object.keys(englishToUrdu).length,
    supportedLanguages: {
      source: ["en"],
      target: ["ur"],
    },
    features: [
      "Contextual phrase translation",
      "Grammar correction",
      "Sentence-level processing",
      "Business terminology",
      "Technical terms",
      "Compound word handling",
    ],
    version: "2.0.0",
    lastUpdated: new Date().toISOString(),
  };
}

/**
 * Get supported translation languages
 * @returns {Object} - Supported source and target languages
 */
export function getSupportedLanguages() {
  return {
    source: ["en"],
    target: ["ur"],
  };
}

/**
 * Add new translation pairs to the dictionary
 * @param {string} englishWord - English word/phrase
 * @param {string} urduTranslation - Urdu translation
 * @returns {boolean} - Success status
 */
export function addToDictionary(englishWord, urduTranslation) {
  if (typeof englishWord === "string" && typeof urduTranslation === "string") {
    englishToUrdu[englishWord.toLowerCase()] = urduTranslation;
    return true;
  }
  return false;
}

/**
 * Check if a word has a translation available
 * @param {string} word - Word to check
 * @returns {boolean} - Whether translation exists
 */
export function hasTranslation(word) {
  return englishToUrdu.hasOwnProperty(word.toLowerCase());
}

/**
 * Get direct translation of a specific word
 * @param {string} word - Word to translate
 * @returns {string|null} - Translation or null if not found
 */
export function getWordTranslation(word) {
  return englishToUrdu[word.toLowerCase()] || null;
}

/**
 * Batch translate multiple phrases
 * @param {Array} phrases - Array of English phrases to translate
 * @returns {Array} - Array of translated phrases
 */
export function batchTranslate(phrases) {
  if (!Array.isArray(phrases)) return [];

  return phrases.map((phrase) => ({
    original: phrase,
    translated: translateToUrduAdvanced(phrase),
    confidence: calculateTranslationConfidence(phrase),
  }));
}

/**
 * Calculate confidence score for translation quality
 * @param {string} text - Original English text
 * @returns {number} - Confidence score (0-100)
 */
function calculateTranslationConfidence(text) {
  if (!text) return 0;

  const words = text.toLowerCase().split(/\s+/);
  const translatedWords = words.filter((word) => hasTranslation(word));

  return Math.round((translatedWords.length / words.length) * 100);
}

/**
 * Export default translation function for backwards compatibility
 */
export default translateToUrdu;
